version: "3.7"
services:
  app:
    container_name: user-manager
    image: vtuanjs/user-manager
    restart: always
    build: 
      context: ../
      args:
        - MONGODB_USER_NAME=dbtest
        - MONGODB_PASSWORD=dbtest
        - MONGODB_SERVICE_NAME=mongo
    env_file: 
      - .env
    environment: 
      MONGODB_SERVICE_NAME: "mongo"
      MONGODB_USER_NAME: "${MONGODB_USER_NAME}"
      MONGODB_PASSWORD: "${MONGODB_PASSWORD}"
    ports:
      - "3002:3001"
  mongo:
    container_name: user-mongo
    image: mongo:4.2.1
    ports:
      - 27019:27017
    env_file: 
      - .env
    environment:
      MONGO_INITDB_DATABASE: "user"
      MONGO_INITDB_ROOT_USERNAME: "${MONGO_INITDB_ROOT_USERNAME}"
      MONGO_INITDB_ROOT_PASSWORD: "${MONGO_INITDB_ROOT_PASSWORD}"
    volumes:
      - ./initdb.js:/docker-entrypoint-initdb.d/initdb.js
      - user-mongo-db:/data/db
      - user-mongo-backup:/backup
volumes:
  user-mongo-db:
  user-mongo-backup:

